name: Build, Test and Deploy to S3

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.19' # Ensure this matches the required version

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install dependencies
      run: npm install --legacy-peer-deps # Add the legacy flag to handle conflicts

    - name: Install @angular/localize
      run: npm install @angular/localize@16.1.4 --save

    - name: Build Angular app for production
      run: ng build

    # Uncomment the below steps if you want to run Cypress tests
    # - name: Install Cypress
    #   run: npm install cypress

    # - name: Run Cypress Tests
    #   run: npx cypress run

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: metodija747
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'dist/my-ecommerce-app'
